language: ruby
rvm:
  - 2.6.3
script:
  - bundle exec jekyll build
branches:
  only:
    - master
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
cache: bundler
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: _site
  github_token: $TRAVIS_DEPLOY_TOKEN
  keep_history: true
  on:
    branch: master
  repo: thelastbraincell/thelastbraincell.github.io
  target_branch: master
notifications:
  email: false
